behaviors:
  GridWorld:
    batch_size: 10
    buffer_init_steps: 1000
    buffer_size: 10
    hidden_units: 128
    init_entcoef: 0.5
    learning_rate: 0.0003
    learning_rate_schedule: constant
    max_steps: 100
    memory_size: 128
    normalize: false
    num_layers: 1
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    sequence_length: 64
    steps_per_update: 10
    summary_freq: 20000
    tau: 0.005
    time_horizon: 5
    trainer: sac
    use_recurrent: false
    vis_encode_type: simple
