behaviors:
  Pyramids:
    batch_size: 10
    buffer_init_steps: 10000
    buffer_size: 10
    hidden_units: 256
    init_entcoef: 0.01
    learning_rate: 0.0003
    learning_rate_schedule: constant
    max_steps: 100
    memory_size: 128
    normalize: false
    num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 2.0
      gail:
        demo_path: Project/Assets/ML-Agents/Examples/Pyramids/Demos/ExpertPyramid.demo
        encoding_size: 128
        gamma: 0.99
        strength: 0.02
        use_actions: true
    sequence_length: 16
    steps_per_update: 10
    summary_freq: 30000
    tau: 0.01
    time_horizon: 128
    trainer: sac
    use_recurrent: false
    vis_encode_type: simple
