behaviors:
  Tennis:
    batch_size: 10
    buffer_init_steps: 0
    buffer_size: 10
    hidden_units: 256
    init_entcoef: 1.0
    learning_rate: 0.0003
    learning_rate_schedule: constant
    max_steps: 100
    memory_size: 128
    normalize: true
    num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    self_play:
      play_against_current_self_ratio: 0.5
      save_steps: 50000
      swap_steps: 50000
      window: 10
    sequence_length: 64
    steps_per_update: 10
    summary_freq: 10000
    tau: 0.005
    time_horizon: 64
    trainer: sac
    use_recurrent: false
    vis_encode_type: simple
