behaviors:
  VisualHallway:
    batch_size: 10
    buffer_init_steps: 0
    buffer_size: 10
    gamma: 0.99
    hidden_units: 128
    init_entcoef: 1.0
    learning_rate: 0.0003
    learning_rate_schedule: constant
    max_steps: 100
    memory_size: 128
    normalize: false
    num_layers: 1
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    sequence_length: 32
    steps_per_update: 10
    summary_freq: 10
    tau: 0.005
    time_horizon: 64
    trainer: sac
    use_recurrent: true
    vis_encode_type: simple
