behaviors:
  WormStatic:
    batch_size: 10
    buffer_init_steps: 2000
    buffer_size: 10
    hidden_units: 512
    init_entcoef: 1.0
    learning_rate: 0.0003
    learning_rate_schedule: constant
    max_steps: 100
    memory_size: 128
    normalize: true
    num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    sequence_length: 64
    steps_per_update: 20
    summary_freq: 30000
    tau: 0.005
    time_horizon: 1000
    trainer: sac
    use_recurrent: false
    vis_encode_type: simple
