behaviors:
  Reacher:
    batch_size: 10
    beta: 0.005
    buffer_size: 10
    epsilon: 0.2
    hidden_units: 128
    lambd: 0.95
    learning_rate: 0.0003
    learning_rate_schedule: linear
    max_steps: 100
    memory_size: 128
    normalize: true
    num_epoch: 3
    num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    sequence_length: 64
    summary_freq: 10
    time_horizon: 1000
    trainer: ppo
    use_recurrent: false
    vis_encode_type: simple
