behaviors:
  SoccerTwos:
    batch_size: 10
    beta: 0.005
    buffer_size: 10
    curriculum:
      measure: progress
      min_lesson_length: 100
      parameters:
        ball_touch:
        - 1.0
        - 0.5
        - 0.0
      signal_smoothing: true
      thresholds:
      - 0.05
      - 0.1
    epsilon: 0.2
    hidden_units: 512
    lambd: 0.95
    learning_rate: 0.0003
    learning_rate_schedule: constant
    max_steps: 100
    memory_size: 128
    normalize: false
    num_epoch: 3
    num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    self_play:
      play_against_latest_model_ratio: 0.5
      save_steps: 50000
      swap_steps: 50000
      team_change: 200000
      window: 10
    sequence_length: 64
    summary_freq: 10
    time_horizon: 1000
    trainer: ppo
    use_recurrent: false
    vis_encode_type: simple
