behaviors:
  Goalie:
    batch_size: 10
    beta: 0.005
    buffer_size: 10
    epsilon: 0.2
    hidden_units: 512
    lambd: 0.95
    learning_rate: 0.0003
    learning_rate_schedule: constant
    max_steps: 100
    memory_size: 128
    normalize: false
    num_epoch: 3
    num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    self_play:
      play_against_latest_model_ratio: 0.5
      save_steps: 50000
      swap_steps: 25000
      team_change: 200000
      window: 10
    sequence_length: 64
    summary_freq: 10000
    time_horizon: 1000
    trainer: ppo
    use_recurrent: false
    vis_encode_type: simple
  Striker:
    batch_size: 10
    beta: 0.005
    buffer_size: 10
    epsilon: 0.2
    hidden_units: 512
    lambd: 0.95
    learning_rate: 0.0003
    learning_rate_schedule: constant
    max_steps: 100
    memory_size: 128
    normalize: false
    num_epoch: 3
    num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    self_play:
      play_against_latest_model_ratio: 0.5
      save_steps: 50000
      swap_steps: 100000
      team_change: 200000
      window: 10
    sequence_length: 64
    summary_freq: 10000
    time_horizon: 1000
    trainer: ppo
    use_recurrent: false
    vis_encode_type: simple
