behaviors:
  BigWallJump:
    batch_size: 10
    beta: 0.005
    buffer_size: 10
    curriculum:
      measure: progress
      min_lesson_length: 100
      parameters:
        big_wall_max_height:
        - 4.0
        - 7.0
        - 8.0
        - 8.0
        big_wall_min_height:
        - 0.0
        - 4.0
        - 6.0
        - 8.0
      signal_smoothing: true
      thresholds:
      - 0.1
      - 0.3
      - 0.5
    epsilon: 0.2
    hidden_units: 256
    lambd: 0.95
    learning_rate: 0.0003
    learning_rate_schedule: linear
    max_steps: 100
    memory_size: 128
    normalize: false
    num_epoch: 3
    num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    sequence_length: 64
    summary_freq: 10
    time_horizon: 128
    trainer: ppo
    use_recurrent: false
    vis_encode_type: simple
  SmallWallJump:
    batch_size: 10
    beta: 0.005
    buffer_size: 10
    curriculum:
      measure: progress
      min_lesson_length: 100
      parameters:
        small_wall_height:
        - 1.5
        - 2.0
        - 2.5
        - 4.0
      signal_smoothing: true
      thresholds:
      - 0.1
      - 0.3
      - 0.5
    epsilon: 0.2
    hidden_units: 256
    lambd: 0.95
    learning_rate: 0.0003
    learning_rate_schedule: linear
    max_steps: 100
    memory_size: 128
    normalize: false
    num_epoch: 3
    num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    sequence_length: 64
    summary_freq: 10
    time_horizon: 128
    trainer: ppo
    use_recurrent: false
    vis_encode_type: simple
