behaviors:
  Pyramids:
    batch_size: 10
    behavioral_cloning:
      demo_path: Project/Assets/ML-Agents/Examples/Pyramids/Demos/ExpertPyramid.demo
      steps: 150000
      strength: 0.5
    beta: 0.01
    buffer_size: 10
    epsilon: 0.2
    hidden_units: 512
    lambd: 0.95
    learning_rate: 0.0003
    max_steps: 100
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    reward_signals:
      curiosity:
        encoding_size: 256
        gamma: 0.99
        strength: 0.02
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        demo_path: Project/Assets/ML-Agents/Examples/Pyramids/Demos/ExpertPyramid.demo
        encoding_size: 128
        gamma: 0.99
        strength: 0.01
    sequence_length: 64
    summary_freq: 30000
    time_horizon: 128
    trainer: ppo
    use_recurrent: false
